### ISSUE TITLE
您好，我的util.java这个文件一直报错，我处理了好久没处理好，您能帮我看看吗？

### ISSUE THREAD

**Issue by yinhainan** [renshen052/mindSubscribe#2]
我本来是想上传图片的，但是一直传不了，是这样子报错的。
D:\mindSubscribe-master\src\utils\Util.java
Error:(184, 39) java: 找不到符号
  符号:   方法 getPart(java.lang.String)
  位置: 类型为javax.servlet.http.HttpServletRequest的变量 request

**Comment by renshen052** [comment]
> 我本来是想上传图片的，但是一直传不了，是这样子报错的。
> D:\mindSubscribe-master\src\utils\Util.java
> Error:(184, 39) java: 找不到符号
> 符号: 方法 getPart(java.lang.String)
> 位置: 类型为javax.servlet.http.HttpServletRequest的变量 request
能更详细一些吗？
想看一下更多的报错信息
你是直接运行mindSubscribe就有这个错误吗？

**Comment by yinhainan** [comment]
是直接运行的时候有这个错，您能加一下我微信吗 18767371003 我微信上和你说
