### ISSUE TITLE
您好，我不太会使用运行这个项目，麻烦可以教我一下吗

### ISSUE THREAD

**Issue by shmily-dian** [renshen052/mindSubscribe#5]
您好，我有点不是太会使用，可以给个联系方式吗，我想请教一下，谢谢

**Comment by renshen052** [comment]
不好意思，很长时间没看github了 

“我不太会使用运行这个项目” 是怎么个不会， 需要说明一下

一般的：这个项目怎么运行你参见 README中的“运行项目”说明

**Comment by renshen052** [comment]
过了很长时间了，估计都不需要了， 这个issue我就关了哈
